apiVersion: v1
kind: Namespace
metadata:
  name: mlops

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
      - name: mlops-api
        image: 408502715812.dkr.ecr.us-east-1.amazonaws.com/mlops-fastapi:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
  namespace: mlops
spec:
  type: LoadBalancer
  selector:
    app: mlops-api
  ports:
    - port: 80
      targetPort: 8000

